version: '3.8'

services:
  db:
    container_name: pg-docker
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=hardwareinv
      - DOCKER_ENV=true #testing this
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - inventory_network

  api:
    build: ./server
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - inventory_network
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./server
        target: /src
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - inventory_network
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./client
        target: /app

# networks:
#   inventory_network:
#     driver: bridge
networks:
  inventory_network:
    driver: bridge
    external: false

volumes:
  db_data:

